band/urls.py
from django.conf.urls import url
import band.views

urlpatterns = [
    url(r'^$', band.views.listing, name="listing"),
    url(r'(?P<id>\d+)/', band.views.details, name='details'),
    url(r'add-to-cart/', band.views.add_to_cart, name='add-to-cart'),
]

cart/urls.py
from django.conf.urls import url
import cart.views


urlpatterns = [
    url(r'^$', cart.views.index, name="index"),
    url(r'^remove-item/$', cart.views.remove_item, name="remove-item"),
    url(r'^confirm/(?P<id>\d+)/$', cart.views.confirm, name="confirm"),
]

shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import band.views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^bands/', include("band.urls", namespace='band')),
    url(r'^housings/', include("housing.urls", namespace='housing')),
    url(r'^cart/', include("cart.urls", namespace='cart')),
    url(r'^profile/', include("myprofile.urls", namespace='profile')),

    url(r'^contacts/$', band.views.contact, name="contact"),
    url(r'^$', band.views.index, name="home"),
]

cart/models.py
# coding=utf-8
from __future__ import unicode_literals
import django.utils.timezone
from django.contrib.auth.models import User

from django.db import models
from band.models import Band
from housing.models import Housing

CART_STATUS = (
    ("OPEN", "Відкрито"),
    ("CLOSED", "Закрито"),
    ("PROGRESS", "В обробці"),
)


class Cart(models.Model):
    status = models.CharField(
        null=False,
        default="OPEN",
        max_length=100,
        choices=CART_STATUS,
    )
    user = models.ForeignKey(
        User,
        blank=False
    )
    bands = models.ManyToManyField(
        Band,
        blank=True
    )
    housings = models.ManyToManyField(
        Housing,
        blank=True
    )
    last_modified = models.DateTimeField(
        auto_now=True,
    )

    def sum(self):
        result = 0
        if self.bands.exists():
            for i in self.bands.all():
                result += i.price
        if self.housings.exists():
            for i in self.housings.all():
                result += i.price
        return result

    def __unicode__(self):
        return "Замовлення №%s, статус: %s, дата: %s" % (
            self.id,
            self.get_status_display(),
            self.last_modified.strftime("%d-%m-%Y")
        )

cart/forms.py
from django import forms
from cart.models import Cart


class CartForm(forms.ModelForm):

    class Meta:
        model = Cart
        fields = '__all__'

cart/views.py
# coding=utf-8
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from band.models import Band
from cart.models import Cart
from cart.utils import *
from housing.models import Housing


@login_required
def index(reuqest):
    user = reuqest.user
    bands = {}
    housings = {}
    if user.cart_set.filter(status="OPEN").exists():
        cart = user.cart_set.get(status="OPEN")
        bands = cart.bands.all()
        housings = cart.housings.all()
    elif user.cart_set.filter(status="PROGRESS").exists():
        cart = user.cart_set.get(status="PROGRESS")
        bands = cart.bands.all()
        housings = cart.housings.all()
    else:
        cart = None
    context = {
        "bands": bands,
        "housings": housings,
        "cart": cart,
    }
    return render(reuqest, "cart/index.html", context)


@csrf_exempt
def remove_item(request):
    user = request.user
    if not user.is_authenticated():
        return http_response_400(
            "403",
            "Permission denied",
        )
    if request.method == "POST":
        if 'id' not in request.POST or 'type' not in request.POST or 'cart' not in request.POST:
            return http_response_400(
                "404",
                "wrong params"
            )
        id = request.POST.get('id')
        type = request.POST.get('type')
        try:
            cart = Cart.objects.get(id=request.POST.get('cart'))
        except:
            return http_response_400("404", "no such cart")
        if cart.status in ['PROGRESS', 'CLOSED']:
            return http_response_400("403", "cart in progress or closed")

        if type == "band":
            if cart.bands.filter(id=id).exists():
                band = Band.objects.get(id=id)
                cart.bands.remove(band)
            else:
                return http_response_400(
                    "404",
                    "no band with id %s in your card" % id,
                )
        elif type == "housing":
            if cart.housings.filter(id=id).exists():
                housing = Housing.objects.get(id=id)
                cart.housings.remove(housing)
            else:
                return http_response_400(
                    "404",
                    "no housing with id %s in your card" % id,
                )
        return HttpResponse(
            json.dumps({
                'sum': str(cart.sum())
            }),
            content_type='application/json',
        )
    else:
        return get_400_response()


@login_required
def confirm(request, id):
    user = request.user
    if user.cart_set.filter(id=id).exists():
        cart = user.cart_set.get(id=id)
    else:
        raise HttpResponseForbidden(u"Замовлення з номером %s не знайдено" % id)
    if cart.status != "OPEN":
        raise HttpResponseForbidden(u"Замовлення з номером %s оброблюється або вже закрита" % id)
    cart.status = "PROGRESS"
    cart.save()
    return HttpResponseRedirect(reverse("profile:orders"))

cart/templates/cart/index.html
{% extends "base.html" %}

{% block content %}
<div class="cart"> 
    {% if cart.status == "OPEN" %}

        {% for band in bands %}
        <div class="element">
            <input class="id" type="hidden" value="{{ band.id }}">
            <a href="{% url "band:details" band.id %}">{{ band }}</a>
            <button id="button-band" type="button" class="remove button-band">
                <span class="glyphicon glyphicon-trash" aria-hidden="true" style="font-size: 24px;"></span>
            </button>
        </div>
        {% endfor %}

        {% for housing in housings %}
        <div class="element">
            <input class="id" type="hidden" value="{{ housing.id }}">
            <a href="{% url "housing:details" housing.id %}">{{ housing }}</a>
            <button id="button-housing" type="button" class="remove button-housing">
                <span class="glyphicon glyphicon-trash" aria-hidden="true" style="font-size: 24px;"></span>
            </button>
        </div>
        {% endfor %}

        <a href="{% url "cart:confirm" cart.id %}">
            <button class="confirm" style="margin-top: 20px; width: 100%; text-align: center;">Підтвердити замовлення</button>
        </a>

        <br><br>
        <span class="main">Сума: $<span id="sum">{{ cart.sum }}</span></span>

    {% elif cart.status == "PROGRESS" %}
        <span class="main"> Ваше замовлення знаходиться у стані обробки </span>
        <span>
            Зачекайте доки з вами зв'яжеться менеджер з продажу та оплатіть
            замовлений товар. Якщо ви хочете відмовитися від зробленого замовлення будь-ласка повідомте про це
            адміністратора, в іншому випадку здійснення покупок на сайті буде неможливе.
        </span>
    {% else %}
        <span class="main"> У вашій корзині ще нема товарів. </span>
        <span> Перейдіть до розділів магазину та оберіть товари для купівлі. </span>
    {% endif %}
</div>
    <script>
        $(".button-band").on("click", function() {
            var node = $(this);
            $.ajax({
                url: "{% url "cart:remove-item" %}",
                method: "POST",
                data: {
                    'id': $(this).parent().children(".id").val(),
                    'type': "band",
                    'cart': {{ cart.id }}
                },
                success:
                        function(data) {
                            $("#sum").html(data.sum);
                            node.parent().remove();
                        },
                error:
                        function(data) {
                            callModal(4);
                            console.log(data);
                        }
            })
        });
        $(".button-housing").on("click", function() {
            var node = $(this);
            $.ajax({
                url: "{% url "cart:remove-item" %}",
                method: "POST",
                data: {
                    'id': $(this).parent().children(".id").val(),
                    'type': "housing",
                    'cart': {{ cart.id }}
                },
                success:
                        function(data) {
                            $("#sum").html(data.sum);
                            node.parent().remove();
                        },
                error:
                        function(data) {
                            callModal(5);
                            console.log(data);
                        }
            })
        })
    </script>
{% endblock %}