band/urls.py
from django.conf.urls import url
import band.views

urlpatterns = [
    url(r'^$', band.views.listing, name="listing"),
    url(r'(?P<id>\d+)/', band.views.details, name='details'),
    url(r'add-to-cart/', band.views.add_to_cart, name='add-to-cart'),
]

housing/urls.py
from django.conf.urls import url
import housing.views


urlpatterns = [
    url(r'^$', housing.views.listing, name="listing"),
    url(r'(?P<id>\d+)/', housing.views.details, name='details'),
    url(r'add-to-cart/', housing.views.add_to_cart, name='add-to-cart'),
]

myprofile/urls.py
from django.conf.urls import url
import myprofile.views


urlpatterns = [
    url(r'^$', myprofile.views.index, name="index"),
    url(r'^housings/$', myprofile.views.housings, name="housings"),
    url(r'^bands/$', myprofile.views.bands, name="bands"),
    url(r'^orders/$', myprofile.views.orders, name="orders"),

    url(r'^housings/new/$', myprofile.views.new_housing, name="new_housing"),
    url(r'^bands/new/$', myprofile.views.new_band, name="new_band"),
    url(r'^housings/(?P<id>\d+)/$', myprofile.views.update_housing, name="update_housing"),
    url(r'^bands/(?P<id>\d+)/$', myprofile.views.update_band, name="update_band"),

    url(r'^remove-housing/$', myprofile.views.remove_housing, name="remove-housing"),
    url(r'^remove-band/$', myprofile.views.remove_band, name="remove-band"),

    url(r'^orders/$', myprofile.views.orders, name="orders"),
    url(r'^orders/(?P<id>\d+)/$', myprofile.views.order, name="order"),

    url(r'^admin/orders/$', myprofile.views.admin_order_listing, name="admin_order_listing"),
    url(r'^admin/orders/(?P<id>\d+)/$', myprofile.views.admin_order_details, name="admin_order_details"),
    url(r'^admin/orders/approve/$', myprofile.views.admin_order_approve, name="approve_order"),
    url(r'^admin/users/$', myprofile.views.admin_users, name="admin_users"),
    url(r'^admin/users/grant/$', myprofile.views.admin_user_grant, name="admin_grant_staff"),
]

shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import band.views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^bands/', include("band.urls", namespace='band')),
    url(r'^housings/', include("housing.urls", namespace='housing')),
    url(r'^cart/', include("cart.urls", namespace='cart')),
    url(r'^profile/', include("myprofile.urls", namespace='profile')),

    url(r'^contacts/$', band.views.contact, name="contact"),
    url(r'^$', band.views.index, name="home"),
]

band/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.contrib.auth.models import User

from django.db import models
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill, ResizeToFit

BAND_STYLE = (
    ('METAL_CORE', 'Металкор'),
    ('ELECTRO_ROCK', 'Електронік рок'),
    ('LYRIC_ROCK', 'Лірик рок'),
    ('METAL', 'Метал'),
    ('POP_ROCK', 'Поп рок'),
    ('FOLK_ROCK', 'Фольк рок'),
    ('ALT_ROCK', 'Альтернативний рок'),
)


class City(models.Model):
    name = models.CharField(
        max_length=128,
        null=False,
        blank=False,
        verbose_name="Ім'я"
    )
    is_capital = models.BooleanField(
        default=False,
        verbose_name="Столиця"
    )

    def __unicode__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = "Місто"
        verbose_name_plural = "Міста"


class Band(models.Model):
    name = models.CharField(
        null=False,
        blank=False,
        max_length=128,
        unique=True,
        verbose_name="Ім'я"
    )
    desc = models.TextField(
        null=True,
        blank=True,
        verbose_name="Опис"
    )
    style = models.CharField(
        null=False,
        blank=False,
        max_length=255,
        choices=BAND_STYLE,
        verbose_name="Стиль"
    )
    city = models.ForeignKey(
        City,
        on_delete=models.CASCADE,
        verbose_name="Місто"
    )
    price = models.IntegerField(
        null=False,
        blank=False,
        verbose_name="Ціна за годину"
    )
    youtube = models.CharField(
        null=True,
        blank=True,
        max_length=255,
        verbose_name="Посилання на відео youtube"
    )
    logo_full = models.ImageField(
        null=True,
        blank=True,
        upload_to='img/bands',
        verbose_name="Логотип",
        help_text="Бажаний розмір 970х500"
    )
    logo = ImageSpecField(
        source='logo_full',
        processors=[ResizeToFill(970, 500)],
        format='JPEG',
        options={'quality': 60}
    )
    logo_listing = ImageSpecField(
        source='logo_full',
        processors=[ResizeToFit(300, 300, mat_color="#000000")],
        format='JPEG',
        options={'quality': 60}
    )
    user = models.ForeignKey(
        User,
        null=False,
        blank=False,
    )

    def __unicode__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = "Гурт"
        verbose_name_plural = "Гурти"


class Actor(models.Model):
    name = models.CharField(
        null=False,
        blank=False,
        max_length=128,
        unique=True,
        verbose_name="Ім'я"
    )
    desc = models.TextField(
        null=True,
        blank=True,
        verbose_name="Опис"
    )
    logo_full = models.ImageField(
        null=True,
        blank=True,
        upload_to='img/actors',
        verbose_name="Логотип"
    )
    logo = ImageSpecField(source='logo_full',
                          processors=[ResizeToFill(970, 500)],
                          format='JPEG',
                          options={'quality': 60})
    band = models.ForeignKey(
        Band,
        null=True,
        blank=True,
        on_delete=models.DO_NOTHING,
        verbose_name="Гурт"
    )
    user = models.ForeignKey(
        User,
        null=False,
        blank=False,
    )

    class Meta:
        verbose_name = "Співак"
        verbose_name_plural = "Співаки"

housing/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.contrib.auth.models import User

from django.db import models
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill
from band.models import City
from myprofile.utils import get_lat_lng


HOUSING_TYPE = (
    ("ART_CAFE", "Арт кафе"),
    ("CLUB", "Клуб"),
    ("PUB", "Паб"),
    ("STADIUM", "Стадіон"),
    ("CONCERT_HALL", "Концертний зал"),
)
EQUIPMENT_TYPE = (
    ("NONE", "Без апаратури"),
    ("ACOUSTIC", "Для акустики"),
    ("5KWT", "До 5 кВт звуку"),
    ("5-10KWT", "Від 5 до 10 кВт звуку"),
    ("10+KWT", "10+ кВт звуку"),
)


class Housing(models.Model):
    name = models.CharField(
        null=False,
        blank=False,
        max_length=100,
        unique=True,
        verbose_name="Ім'я"
    )
    desc = models.TextField(
        null=True,
        blank=True,
        verbose_name="Опис"
    )
    type = models.CharField(
        choices=HOUSING_TYPE,
        max_length=100,
        null=False,
        blank=False,
        verbose_name="Тип проміщення"
    )
    price = models.IntegerField(
        null=False,
        blank=False,
        verbose_name="Ціна за годину оренди"
    )
    street = models.CharField(
        blank=True,
        null=False,
        default="",
        max_length=100,
        verbose_name="Вулиця"
    )
    number = models.CharField(
        blank=True,
        null=False,
        default="",
        max_length=10,
        verbose_name="Номер будівлі"
    )
    city = models.ForeignKey(
        City,
        null=False,
        blank=False,
        max_length=100,
        verbose_name="Місто",
    )
    region = models.CharField(
        blank=True,
        null=False,
        default="",
        max_length=100,
        verbose_name="Область",
    )
    location = models.CharField(
        blank=True,
        null=False,
        default="0,0",
        max_length=100,
    )
    capacity = models.IntegerField(
        null=False,
        blank=False,
        verbose_name="Місткість",
    )
    equipment = models.CharField(
        choices=EQUIPMENT_TYPE,
        max_length=100,
        null=False,
        blank=False,
        verbose_name="Обладнання",
    )
    logo_full = models.ImageField(
        null=True,
        blank=True,
        upload_to='img/housings',
        verbose_name="Логотип",
    )
    logo = ImageSpecField(source='logo_full',
                          processors=[ResizeToFill(970, 500)],
                          format='JPEG',
                          options={'quality': 60})
    user = models.ForeignKey(
        User,
        null=False,
        blank=False,
    )

    def address(self):
        return "%s %s %s %s" % (
            self.city,
            u", вул. " + self.street if self.street else "",
            u", буд. " + self.number if self.number else "",
            u", обл. " + self.region if self.region else "",
        )

    def save(self, *args, **kwargs):
        # Add + between fields with values:
        location = '+'.join(filter(None, (u"вул. ", self.street, self.number, self.city.name, self.region)))
        # Attempt to get latitude/longitude from Google Geocoder service v.3:
        self.location = get_lat_lng(location)
        super(Housing, self).save(*args, **kwargs)

    def __unicode__(self):
        return "%s: %s" % (self.get_type_display(), self.name)

    class Meta:
        verbose_name = "Концертна зала"
        verbose_name_plural = "Концертні зали"

myprofile/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

band/forms.py
from django import forms
from .models import *


class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ['name', 'is_capital']


class ActorForm(forms.ModelForm):
    class Meta:
        model = Actor
        fields = '__all__'
        exclude = ['logo']


class ActorUserForm(forms.ModelForm):
    class Meta:
        model = Actor
        fields = '__all__'
        exclude = ['logo', 'user']


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        fields = '__all__'
        exclude = ['logo']


class BandUserForm(forms.ModelForm):
    class Meta:
        model = Band
        fields = '__all__'
        exclude = ['logo', 'user']

housing/forms.py
# coding=utf-8
from django import forms
from housing.models import *


class HousingForm(forms.ModelForm):

    class Meta:
        model = Housing
        fields = '__all__'
        exclude = ('logo',)


class HousingUserForm(forms.ModelForm):

    class Meta:
        model = Housing
        fields = '__all__'
        exclude = ('user', 'logo',)


class HousingMapForm(forms.ModelForm):

    class Meta:
        model = Housing
        fields = '__all__'
        exclude = ('user', 'logo', 'location')

band/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from band.models import Band
from housing.models import Housing
from band.utils import *
from cart.models import Cart


def index(request):
    housings = Housing.objects.all().order_by('?')[:3]
    bands = list(Band.objects.all().order_by('?')[:5])
    context = {
        "band_active": bands[0],
        "bands": bands[1:],
        "housings": housings,
    }
    return render(request, "index.html", context)


def contact(request):
    return render(request, "contact.html", context={})


def listing(request):
    query = Band.objects.all()
    if 'search' in request.GET:
        search = request.GET.get('search')
        query = query.filter(
            Q(name__icontains=search))
    paginator = Paginator(query.order_by("name"), 9)
    page = request.GET.get('page')
    try:
        bands = paginator.page(page)
    except PageNotAnInteger:
        bands = paginator.page(1)
        page = 1
    except EmptyPage:
        bands = paginator.page(paginator.num_pages)
        page = paginator.num_pages
    context = {
        "bands": bands,
        "pages": range(1, paginator.num_pages+1),
        "active_page": int(page),
    }
    return render(request, "band/listing.html", context)


def details(request, id):
    band = get_object_or_404(Band, id=id)
    context = {
        "band": band,
    }
    return render(request, "band/details.html", context)


@csrf_exempt
def add_to_cart(request):
    if not request.user.is_authenticated():
        return http_response_400(
            "403",
            "Permission denied",
        )
    if request.method == "POST":
        user = request.user
        if user.cart_set.filter(status="PROGRESS").exists():
            return http_response_400("403", "cart in progress")
        elif user.cart_set.filter(status="OPEN").exists():
            cart = user.cart_set.get(status="OPEN")
        else:
            cart = Cart()
            cart.user = request.user
            cart.status = "OPEN"
            cart.save()
        if not 'id' in request.POST:
            return http_response_400(
                "404",
                "wrong params"
            )
        id = request.POST.get('id')
        try:
            band = Band.objects.get(id=id)
        except:
            return http_response_400(
                "404",
                "no band with id %s" % id,
            )
        if band not in cart.bands.all():
            cart.bands.add(band)
            return HttpResponse(
                status=200,
            )
        else:
            return http_response_400(
                "400",
                "band is already in the cart",
            )
    else:
        return get_400_response()

housing/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from cart.models import Cart
from housing.models import Housing
from housing.utils import get_400_response, http_response_400


def listing(request):
    query = Housing.objects.all()
    if 'search' in request.GET:
        search = request.GET.get('search')
        query = query.filter(
            Q(name__icontains=search))
    paginator = Paginator(query.order_by("name"), 5)
    page = request.GET.get('page')
    try:
        housings = paginator.page(page)
    except PageNotAnInteger:
        housings = paginator.page(1)
        page = 1
    except EmptyPage:
        housings = paginator.page(paginator.num_pages)
        page = paginator.num_pages
    context = {
        "housings": housings,
        "pages": range(1, paginator.num_pages+1),
        "active_page": int(page),
    }
    return render(request, "housing/listing.html", context)


def details(request, id):
    housing = get_object_or_404(Housing, id=id)
    context = {
        "housing": housing,
    }
    return render(request, "housing/details.html", context)


@csrf_exempt
def add_to_cart(request):
    if not request.user.is_authenticated():
        return http_response_400(
            "403",
            "Permission denied",
        )
    if request.method == "POST":
        user = request.user
        if user.cart_set.filter(status="PROGRESS").exists():
            return http_response_400("403", "cart in progress")
        elif user.cart_set.filter(status="OPEN").exists():
            cart = user.cart_set.get(status="OPEN")
        else:
            cart = Cart()
            cart.user = request.user
            cart.status = "OPEN"
            cart.save()
        if not 'id' in request.POST:
            return http_response_400(
                "404",
                "wrong params"
            )
        id = request.POST.get('id')
        try:
            housing = Housing.objects.get(id=id)
        except:
            return http_response_400(
                "404",
                "no housing with id %s" % id,
            )
        if housing not in cart.housings.all():
            cart.housings.add(housing)
            return HttpResponse(
                status=200,
            )
        else:
            return http_response_400(
                "400",
                "housing is already in the cart",
            )
    else:
        return get_400_response()

myprofile/templates/myprofile/bands.html
{% extends "myprofile/base.html" %}

{% block content %}
<div class="userpage-right">
    <h1>Мої гурти</h1><br>
    {% include "search.html" %}

    {% for band in bands %}
        <div class="item">
            <input class="id" type="hidden" value="{{ band.id }}">
            <a href="{% url "profile:update_band" band.id %}">{{ band }}</a>
            <button class="remove" type="button">
                <span class="glyphicon glyphicon-trash" aria-hidden="true" style="font-size: 24px;"></span>
            </button>
        </div>
    {% endfor %}

    <a href="{% url "profile:new_band" %}">Додати новий гурт</a>

    {% if bands|length > 0 %}
    {% include "paginator.html" %}
    {% endif %}
</div>
    <script>
        $(".remove").on("click", function() {
            var node = $(this);
            $.ajax({
                url: "{% url "profile:remove-band" %}",
                method: "POST",
                data: {
                    'id': $(this).parent().children(".id").val()
                },
                success:
                        function(data) {
                            node.parent().remove();
                        },
                error:
                        function(data) {
                            callModal(5);
                            console.log(data);
                        }
            })
        })
    </script>
{% endblock %}

myprofile/templates/myprofile/base.html
{% extends "base.html" %}

{% block page %}
<div class="userpage-left">
    <span class="head">МЕНЮ:</span>
    <a href="{% url "account_change_password" %}">Змінити пароль</a>
    <a href="{% url "account_email" %}">Emails</a>
    <a href="{% url "socialaccount_connections" %}">Соціальні мережі</a>
    <a href="{% url "profile:bands" %}">Мої гурти</a>
    <a href="{% url "profile:housings" %}">Мої концертні зали</a>
    <a href="{% url "profile:orders" %}">Історія замовлень</a>

    {% if request.user.is_staff or request.user.is_superuser %}
        <hr>
        <a href="{% url "profile:admin_order_listing" %}">Адміністрування замовлень</a>
        <a href="{% url "profile:admin_users" %}">Адміністрування користувачів</a>
    {% endif %}
</div>
    {% block content %}
    {% endblock %}
{% endblock %}

myprofile/templates/myprofile/housings.html
{% extends "myprofile/base.html" %}

{% block content %}
<div class="userpage-right">
    <h1>Мої концертні зали</h1><br>
    {% include "search.html" %}

    {% for housing in housings %}
        <div class="item">
            <input class="id" type="hidden" value="{{ housing.id }}">
            <a href="{% url "profile:update_housing" housing.id %}">{{ housing }}</a>
            <button class="remove" type="button">
                <span class="glyphicon glyphicon-trash" aria-hidden="true" style="font-size: 24px;"></span>
            </button>
        </div>
    {% endfor %}

    <a href="{% url "profile:new_housing" %}">Додати нову концертну залу</a>

    {% if housings|length > 0 %}
    {% include "paginator.html" %}
    {% endif %}
</div>
    <script>
        $(".remove").on("click", function() {
            var node = $(this);
            $.ajax({
                url: "{% url "profile:remove-housing" %}",
                method: "POST",
                data: {
                    'id': $(this).parent().children(".id").val()
                },
                success:
                        function(data) {
                            node.parent().remove();
                        },
                error:
                        function(data) {
                            callModal(5);
                            console.log(data);
                        }
            })
        })
    </script>
{% endblock %}

myprofile/templates/myprofile/index.html
{% extends "myprofile/base.html" %}

{% block content %}

<div class="userpage-right">
    {% with request.user as user %}
        <span class="normal">Привiт,</span> 
       	<span class="bold">{{ user }}</span><br>
       	<span class="normal">{{ user.email }}</span>
    {% endwith %}
</div>
{% endblock %}

myprofile/templates/myprofile/order.html
{% extends "myprofile/base.html" %}

{% block content %}
<div class="userpage-right">
	<h1>Замовлення №{{ cart.id }} від {{ cart.last_modified|date:"d-M-Y" }}</h1><br>
    {% for band in cart.bands.all %}
        <a href="{% url "band:details" band.id %}">{{ band }}</a>
    {% endfor %}

    {% for housing in cart.housings.all %}
        <a href="{% url "housing:details" housing.id %}">{{ housing }}</a>
    {% endfor %}

    <span class="normal" style="width:100%; text-align:center;">Сума: ${{ cart.sum }}</span>
</div>
{% endblock %}

myprofile/templates/myprofile/orders.html
{% extends "myprofile/base.html" %}

{% block content %}
<div class="userpage-right">
	<h1>Історія замовлень</h1><br>
    {% for cart in carts %}
        <a href="{% url "profile:order" cart.id %}">{{ cart }}</a>
    {% endfor %}
    <br>

    {% if carts|length > 0 %}
    {% include "paginator.html" %}
    {% endif %}
</div>
{% endblock %}