band/urls.py
from django.conf.urls import url
import band.views

urlpatterns = [
    url(r'^$', band.views.listing, name="listing"),
    url(r'(?P<id>\d+)/', band.views.details, name='details'),
    url(r'add-to-cart/', band.views.add_to_cart, name='add-to-cart'),
]

myprofile/urls.py
from django.conf.urls import url
import myprofile.views


urlpatterns = [
    url(r'^$', myprofile.views.index, name="index"),
    url(r'^housings/$', myprofile.views.housings, name="housings"),
    url(r'^bands/$', myprofile.views.bands, name="bands"),
    url(r'^orders/$', myprofile.views.orders, name="orders"),

    url(r'^housings/new/$', myprofile.views.new_housing, name="new_housing"),
    url(r'^bands/new/$', myprofile.views.new_band, name="new_band"),
    url(r'^housings/(?P<id>\d+)/$', myprofile.views.update_housing, name="update_housing"),
    url(r'^bands/(?P<id>\d+)/$', myprofile.views.update_band, name="update_band"),

    url(r'^remove-housing/$', myprofile.views.remove_housing, name="remove-housing"),
    url(r'^remove-band/$', myprofile.views.remove_band, name="remove-band"),

    url(r'^orders/$', myprofile.views.orders, name="orders"),
    url(r'^orders/(?P<id>\d+)/$', myprofile.views.order, name="order"),

    url(r'^admin/orders/$', myprofile.views.admin_order_listing, name="admin_order_listing"),
    url(r'^admin/orders/(?P<id>\d+)/$', myprofile.views.admin_order_details, name="admin_order_details"),
    url(r'^admin/orders/approve/$', myprofile.views.admin_order_approve, name="approve_order"),
    url(r'^admin/users/$', myprofile.views.admin_users, name="admin_users"),
    url(r'^admin/users/grant/$', myprofile.views.admin_user_grant, name="admin_grant_staff"),
]

shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import band.views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^bands/', include("band.urls", namespace='band')),
    url(r'^housings/', include("housing.urls", namespace='housing')),
    url(r'^cart/', include("cart.urls", namespace='cart')),
    url(r'^profile/', include("myprofile.urls", namespace='profile')),

    url(r'^contacts/$', band.views.contact, name="contact"),
    url(r'^$', band.views.index, name="home"),
]

myprofile/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

myprofile/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from band.forms import BandUserForm
from band.models import Band, Actor
from cart.models import Cart
from housing.forms import HousingUserForm, HousingMapForm
from housing.models import Housing
from myprofile.utils import *


@login_required
def index(request):
    context = {

    }
    return render(request, "myprofile/index.html", context)


@login_required
def bands(request):
    query = request.user.band_set.all()
    if 'search' in request.GET:
        search = request.GET.get('search')
        query = query.filter(
            Q(name__icontains=search))
    paginator = Paginator(query.order_by("name"), 10)
    page = request.GET.get('page')
    try:
        bands = paginator.page(page)
    except PageNotAnInteger:
        bands = paginator.page(1)
        page = 1
    except EmptyPage:
        bands = paginator.page(paginator.num_pages)
        page = paginator.num_pages
    context = {
        "bands": bands,
        "pages": range(1, paginator.num_pages+1),
        "active_page": int(page),
    }
    return render(request, "myprofile/bands.html", context)


@login_required
def housings(request):
    query = request.user.housing_set.all()
    if 'search' in request.GET:
        search = request.GET.get('search')
        query = query.filter(
            Q(name__icontains=search))
    paginator = Paginator(query.order_by("name"), 10)
    page = request.GET.get('page')
    try:
        housings = paginator.page(page)
    except PageNotAnInteger:
        housings = paginator.page(1)
        page = 1
    except EmptyPage:
        housings = paginator.page(paginator.num_pages)
        page = paginator.num_pages
    context = {
        "housings": housings,
        "pages": range(1, paginator.num_pages+1),
        "active_page": int(page),
    }
    return render(request, "myprofile/housings.html", context)


@login_required
def orders(request):
    user = request.user
    context = {
        "carts": user.cart_set.all()
    }
    return render(request, "myprofile/orders.html", context)


@login_required
def new_housing(request):
    user = request.user
    if request.method == "POST":
        form = HousingMapForm(request.POST, request.FILES)
        if form.is_valid():
            housing = form.save(commit=False)
            housing.user = user
            housing.save()
            return HttpResponseRedirect(reverse("profile:housings"))
    else:
        form = HousingMapForm()
    context = {
        "form": form,
    }
    return render(request, "myprofile/new/housing.html", context)


@login_required
def update_housing(request, id):
    user = request.user
    housing = get_object_or_404(Housing, id=id)
    if request.method == "POST":
        form = HousingMapForm(request.POST, request.FILES, instance=housing)
        if form.is_valid():
            housing = form.save(commit=False)
            housing.user = user
            housing.save()
            return HttpResponseRedirect(reverse("profile:housings"))
    else:
        form = HousingMapForm(instance=housing)
    context = {
        "form": form,
    }
    return render(request, "myprofile/new/housing.html", context)


@login_required
def update_band(request, id):
    user = request.user
    band = get_object_or_404(Band, id=id)
    if request.method == "POST":
        form = BandUserForm(request.POST, request.FILES, instance=band)
        if form.is_valid():
            band = form.save(commit=False)
            band.user = user
            band.save()
            return HttpResponseRedirect(reverse("profile:bands"))
    else:
        form = BandUserForm(instance=band)
    context = {
        "form": form,
    }
    return render(request, "myprofile/new/housing.html", context)


@login_required
def new_band(request):
    user = request.user
    if request.method == "POST":
        form = BandUserForm(request.POST, request.FILES)
        if request.POST:
            if form.is_valid():
                band = form.save(commit=False)
                band.user = user
                band.save()
                return HttpResponseRedirect(reverse("profile:bands"))
    else:
        form = BandUserForm()
    context = {
        "form": form,
    }
    return render(request, "myprofile/new/band.html", context)


@csrf_exempt
def remove_housing(request):
    if request.method == "POST":
        user = request.user
        if 'id' not in request.POST:
            return http_response_400(
                "404",
                "wrong params"
            )
        id = request.POST.get("id")
        if user.housing_set.filter(id=id).exists():
            housing = Housing.objects.get(id=id)
        else:
            return http_response_400("404", "no such housing")
        housing.delete()
        return HttpResponse(status=200, )
    else:
        return get_400_response()


@csrf_exempt
def remove_band(request):
    if request.method == "POST":
        user = request.user
        if 'id' not in request.POST:
            return http_response_400(
                "404",
                "wrong params"
            )
        id = request.POST.get("id")
        if user.band_set.filter(id=id).exists():
            band = Band.objects.get(id=id)
        else:
            return http_response_400("404", "no such housing")
        band.delete()
        return HttpResponse(status=200, )
    else:
        return get_400_response()


@login_required
def orders(request):
    paginator = Paginator(request.user.cart_set.order_by("-id"), 10)
    page = request.GET.get('page')
    try:
        carts = paginator.page(page)
    except PageNotAnInteger:
        carts = paginator.page(1)
        page = 1
    except EmptyPage:
        carts = paginator.page(paginator.num_pages)
        page = paginator.num_pages
    context = {
        "carts": carts,
        "pages": range(1, paginator.num_pages+1),
        "active_page": int(page),
    }
    return render(request, "myprofile/orders.html", context)


@login_required
def order(request, id):
    cart = get_object_or_404(Cart, id=id, user_id=request.user.id)
    context = {
        "cart": cart,
    }
    return render(request, "myprofile/order.html", context)


@login_required
@user_passes_test(lambda u: u.is_staff or u.is_superuser)
def admin_order_listing(request):
    query = Cart.objects.filter(Q(status="CLOSED") | Q(status="PROGRESS"))
    if 'search' in request.GET:
        search = request.GET.get('search')
        query = query.filter(
            Q(user__username__icontains=search) |
            Q(user__first_name__icontains=search) |
            Q(user__email__icontains=search))
    paginator = Paginator(query.order_by("-last_modified"), 10)
    page = request.GET.get('page')
    try:
        carts = paginator.page(page)
    except PageNotAnInteger:
        carts = paginator.page(1)
        page = 1
    except EmptyPage:
        carts = paginator.page(paginator.num_pages)
        page = paginator.num_pages
    context = {
        "carts": carts,
        "pages": range(1, paginator.num_pages+1),
        "active_page": int(page),
    }
    return render(request, "myprofile/admin/orders.html", context)


@login_required
@user_passes_test(lambda u: u.is_staff or u.is_superuser)
def admin_order_details(request, id):
    cart = get_object_or_404(Cart, id=id)
    context = {
        "cart": cart,
    }
    return render(request, "myprofile/admin/order_details.html", context)


@csrf_exempt
def admin_order_approve(request):
    if request.method == "POST":
        user = request.user
        if not (user.is_staff or user.is_superuser):
            return http_response_400(
                "403",
                "permission denied"
            )
        if 'id' not in request.POST:
            return http_response_400(
                "404",
                "wrong params"
            )
        id = request.POST.get("id")
        if Cart.objects.filter(id=id).filter(status="PROGRESS").exists():
            cart = Cart.objects.get(id=id)
        else:
            return http_response_400("404", "cart with id %s doesn't exist or already approved" % id)
        cart.status = "CLOSED"
        cart.save()
        return HttpResponse(status=200, )
    else:
        get_400_response()


@login_required
@user_passes_test(lambda u: u.is_staff or u.is_superuser)
def admin_users(request):
    query = User.objects.all()
    if 'search' in request.GET:
        search = request.GET.get('search')
        query = query.filter(
            Q(username__icontains=search) |
            Q(first_name__icontains=search) |
            Q(email__icontains=search))
    paginator = Paginator(query.order_by("username"), 20)
    page = request.GET.get('page')
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
        page = 1
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
        page = paginator.num_pages
    context = {
        "users": users,
        "pages": range(1, paginator.num_pages + 1),
        "active_page": int(page),
    }
    return render(request, "myprofile/admin/users.html", context)


@csrf_exempt
def admin_user_grant(request):
    if request.method == "POST":
        user = request.user
        if not (user.is_staff or user.is_superuser):
            return http_response_400(
                "403",
                "permission denied"
            )
        if 'id' not in request.POST:
            return http_response_400(
                "404",
                "wrong params"
            )

myprofile/templates/myprofile/admin/order_details.html
{% extends "myprofile/base.html" %}

{% block content %}
<div class="userpage-right">
	<center>
	<br><br>
	<span class="bold">
        <p>Замовлення №{{ cart.id }}</p>
        <p>Користувач: {{ cart.user }}</p>
        <p>Статус: {{ cart.get_status_display }}</p>
        <p>Дата: {{ cart.last_modified|date:"d-M-Y" }}</p>
    </span>
    {% for band in cart.bands.all %}
        <a href="{% url "band:details" band.id %}">{{ band }}</a>
    {% endfor %}

    {% for housing in cart.housings.all %}
        <a href="{% url "housing:details" housing.id %}">{{ housing }}</a>
    {% endfor %}
	<br>
	<span class="normal">Сума: ${{ cart.sum }}</span>
	</center>
</div>
{% endblock %}

myprofile/templates/myprofile/admin/orders.html
{% extends "myprofile/base.html" %}

{% block content %}
<div class="userpage-right">
    <h1>Адміністрування замовлень</h1><br>
    {% include "search.html" %}

    <table class="table">
        <thead>
            <tr>
                <th width="5%">№</th>
                <th width="35%">Користувач</th>
                <th width="15%">Статус</th>
                <th width="15%">Дата</th>
                <th width="15%">Операція</th>
            </tr>
        </thead>
        <tbody>
        {% for cart in carts %}
            <tr>
                <td>{{ cart.id }}</td>
                <td>{{ cart.user }}</td>
                <td id= "{{ cart.id }}-status" class="status">{{ cart.get_status_display }}</td>
                <td>{{ cart.last_modified|date:"d-M-Y" }}</td>
                <td>
                    {% if cart.status == "PROGRESS" %}
                        <input type="hidden" class="id" value="{{ cart.id }}">
                        <button style="margin-top: 0; " class="confirm" type="button">Підтвердити</button>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if carts|length > 0 %}
    {% include "paginator.html" %}
    {% endif %}
</div>

    <script>
        $(".confirm").on("click", function() {
            var node = $(this);
            $.ajax({
                url: "{% url "profile:approve_order" %}",
                method: "POST",
                data: {
                    'id': node.parent().children(".id").val()
                },
                success:
                        function(data) {
                            node.closest("tr").children("td.status").html("Closed");
                            node.parent().children("button").remove();
                       },
                error:
                        function(data) {
                            callModal(2);
                        }
            });
        });

        $('.table').find('tbody').on('click', 'tr', function () {
            order_id = $(this).children()[0].innerHTML;
            window.location.href = "/profile/admin/orders/" + order_id + "/";
        });

        $(document).ready(function() {
            $('tbody tr').hover(
              function() {
                  node = $(this);
                  node.attr("class", node.attr("class") + " enter");
              }, function() {
                        node = $(this);
                        node.attr("class", node.attr("class").replace("enter", ""));
              }
            );
        });

    </script>

{% endblock %}

myprofile/templates/myprofile/admin/users.html
{% extends "myprofile/base.html" %}

{% block content %}
<div class="userpage-right">
    <h1>Адміністрування користувачів</h1><br>
    {% include "search.html" %}

    <table class="table">
        <thead>
            <tr>
                <th width="5%">№</th>
                <th width="25%">Логін</th>
                <th width="35%">Email</th>
                <th width="35%">Операція</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                <td>
                    {% if not user.is_staff and not user.is_superuser %}
                        <input type="hidden" class="id" value="{{ user.id }}">
                        <button class="btn btn-xs btn-success" type="button">Зробити адміністратором</button>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if users|length > 0 %}
    {% include "paginator.html" %}
    {% endif %}
</div>

    <script>
        $(".grant").on("click", function() {
            var node = $(this);
            $.ajax({
                url: "{% url "profile:admin_grant_staff" %}",
                method: "POST",
                data: {
                    'id': $(this).parent().children(".id").val()
                },
                success:
                        function(data) {
                            node.parent().children("button").remove();
                       },
                error:
                        function(data) {
                            callModal(3);
                        }
            })
        })
    </script>

{% endblock %}