band/urls.py
from django.conf.urls import url
import band.views

urlpatterns = [
    url(r'^$', band.views.listing, name="listing"),
    url(r'(?P<id>\d+)/', band.views.details, name='details'),
    url(r'add-to-cart/', band.views.add_to_cart, name='add-to-cart'),
]

cart/urls.py
from django.conf.urls import url
import cart.views


urlpatterns = [
    url(r'^$', cart.views.index, name="index"),
    url(r'^remove-item/$', cart.views.remove_item, name="remove-item"),
    url(r'^confirm/(?P<id>\d+)/$', cart.views.confirm, name="confirm"),
]

shop/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import band.views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^bands/', include("band.urls", namespace='band')),
    url(r'^housings/', include("housing.urls", namespace='housing')),
    url(r'^cart/', include("cart.urls", namespace='cart')),
    url(r'^profile/', include("myprofile.urls", namespace='profile')),

    url(r'^contacts/$', band.views.contact, name="contact"),
    url(r'^$', band.views.index, name="home"),
]

housing/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.contrib.auth.models import User

from django.db import models
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill
from band.models import City
from myprofile.utils import get_lat_lng


HOUSING_TYPE = (
    ("ART_CAFE", "Арт кафе"),
    ("CLUB", "Клуб"),
    ("PUB", "Паб"),
    ("STADIUM", "Стадіон"),
    ("CONCERT_HALL", "Концертний зал"),
)
EQUIPMENT_TYPE = (
    ("NONE", "Без апаратури"),
    ("ACOUSTIC", "Для акустики"),
    ("5KWT", "До 5 кВт звуку"),
    ("5-10KWT", "Від 5 до 10 кВт звуку"),
    ("10+KWT", "10+ кВт звуку"),
)


class Housing(models.Model):
    name = models.CharField(
        null=False,
        blank=False,
        max_length=100,
        unique=True,
        verbose_name="Ім'я"
    )
    desc = models.TextField(
        null=True,
        blank=True,
        verbose_name="Опис"
    )
    type = models.CharField(
        choices=HOUSING_TYPE,
        max_length=100,
        null=False,
        blank=False,
        verbose_name="Тип проміщення"
    )
    price = models.IntegerField(
        null=False,
        blank=False,
        verbose_name="Ціна за годину оренди"
    )
    street = models.CharField(
        blank=True,
        null=False,
        default="",
        max_length=100,
        verbose_name="Вулиця"
    )
    number = models.CharField(
        blank=True,
        null=False,
        default="",
        max_length=10,
        verbose_name="Номер будівлі"
    )
    city = models.ForeignKey(
        City,
        null=False,
        blank=False,
        max_length=100,
        verbose_name="Місто",
    )
    region = models.CharField(
        blank=True,
        null=False,
        default="",
        max_length=100,
        verbose_name="Область",
    )
    location = models.CharField(
        blank=True,
        null=False,
        default="0,0",
        max_length=100,
    )
    capacity = models.IntegerField(
        null=False,
        blank=False,
        verbose_name="Місткість",
    )
    equipment = models.CharField(
        choices=EQUIPMENT_TYPE,
        max_length=100,
        null=False,
        blank=False,
        verbose_name="Обладнання",
    )
    logo_full = models.ImageField(
        null=True,
        blank=True,
        upload_to='img/housings',
        verbose_name="Логотип",
    )
    logo = ImageSpecField(source='logo_full',
                          processors=[ResizeToFill(970, 500)],
                          format='JPEG',
                          options={'quality': 60})
    user = models.ForeignKey(
        User,
        null=False,
        blank=False,
    )

    def address(self):
        return "%s %s %s %s" % (
            self.city,
            u", вул. " + self.street if self.street else "",
            u", буд. " + self.number if self.number else "",
            u", обл. " + self.region if self.region else "",
        )

    def save(self, *args, **kwargs):
        # Add + between fields with values:
        location = '+'.join(filter(None, (u"вул. ", self.street, self.number, self.city.name, self.region)))
        # Attempt to get latitude/longitude from Google Geocoder service v.3:
        self.location = get_lat_lng(location)
        super(Housing, self).save(*args, **kwargs)

    def __unicode__(self):
        return "%s: %s" % (self.get_type_display(), self.name)

    class Meta:
        verbose_name = "Концертна зала"
        verbose_name_plural = "Концертні зали"

templates/base.html
{% load staticfiles %}
{% load i18n %}
{% load django_bootstrap_breadcrumbs %}

<html lang="en" xmlns="http://www.w3.org/1999/html">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mycss.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <!--script src="https://use.fontawesome.com/50b3afe434.js"></script-->

{#    <link href="{% static 'img/favicon2.png' %}" rel="shortcut icon"  type="image/png">#}

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

    <title>{% block head_title %}Shop{% endblock %}</title>

    <style>
      {% block style %}
      {% endblock %}
    </style>

  </head>

  <body>

    {% include "navbar.html" %}
    {% include "popup.html" %}

    {% if messages %}

    {% for message in messages %}
      {% if 'success' in message.tags %}
        <div class="alert alert-success fade in">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <strong>Успіх!</strong> {{ message }}
        </div>
      {% elif 'info' in message.tags %}
        <div class="alert alert-info">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <strong>Інформація!</strong> {{ message }}
        </div>
      {% elif 'warning' in message.tags %}
        <div class="alert alert-warning">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <strong>Попередження!</strong> {{ message }}
        </div>
      {% elif 'danger' in message.tags %}
        <div class="alert alert-danger">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <strong>Помилка!</strong> {{ message }}
        </div>
      {% endif %}
    {% endfor %}

    {% endif %}


    <div class="container content">

        {% block page %}
            {% block content %}
            {% endblock %}
        {% endblock %}


    </div>

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'smart-selects/admin/js/chainedfk.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/page.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popup-activator.js' %}"  charset="UTF-8"></script>

  </body>
{% include "footer.html" %}
</html>

templates/contact.html
{% extends "base.html" %}

{% block content %}
<div class="contact">
    <span class="main"> Контакти </span>
    <span>
        <p>За детальною інформацією звертатися на пошту</p>
        <p>ubog291@gmail.com</p>
        <p>або за мобільними телефонами</p>
        <p>+38 (097) 595 78 39</p>
        <p>+38 (093) 920 32 80</p>
        <p>Також можна звернутися на сторінку в соц. мережах:</p>
    </span>
    <ul class="social-section">
    	<li><a href="http://facebook.com/" class="icon fa fa-facebook"></a></li>
		<li><a href="https://new.vk.com/id217289016" class="icon fa fa-vk"></a></li>
		<li><a href="http://plus.google.com/" class="icon fa fa-google-plus"></a></li>
		<li><a href="https://www.youtube.com/" class="icon fa fa-youtube"></a></li>
    </ul>
</div>
{% endblock %}

templates/footer.html
<footer id="footer" class="footer hide">
  <div class="container">
      <p>
          &copy; 2016 Bodyan
                &nbsp;&nbsp;&nbsp;&nbsp;
          Design by <a href="https://new.vk.com/id217289016">Bogdan Ustyanskiy</a>
      </p>
  </div>
</footer>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      {% for band in bands %}
        <li data-target="#myCarousel" data-slide-to="{{ forloop.counter|add:"1" }}"></li>
      {% endfor %}
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
  	<div class="item active">
        <img src="{{ band_active.logo|band_logo_or_default }}" alt="{{ band_active.name }}">
        <div class="carousel-caption">
            <a href="{% url "band:details" band_active.id %}"><h3>{{ band_active.name }}</h3></a>
        </div>
    </div>

  	{% for band in bands %}
        <div class="item">
            <img src="{{ band.logo|band_logo_or_default }}" alt="{{ band.name }}">
            <div class="carousel-caption">
                <a href="{% url "band:details" band.id %}"><h3>{{ band.name }}</h3></a>
            </div>
        </div>
    {% endfor %}
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Попередня</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Наступна</span>
  </a>
</div>

<div class="view">
	<span class="title">Вітаємо вас на сайті з організації концертів</span>
	<span class="description">
        Ви організатор рок концертів, чи хочете щоб ми організували концерт з вашими улюбленими гуртами
        тоді вам до нас. Наш сервіс допоможе вам організувати концерт, знайти потрібні вам рок гурти
        чи концертні зали.
    </span>
	<a href="/bands/"><span style="font-size: 28px;">Перейти до усіх гуртів</span></a>
	<hr>
	<span>Наші пропозиції по місцях проведення</span><br>
</div>
<div class="housing-container">
    {% for housing in housings %}
    
  <a href="{% url "housing:details" housing.id %}">
	<div class="element item">
	    <input class="id" type="hidden" value="{{ housing.id }}">
	    <div class="text-back">        
          <span class="head">{{ housing.name }}</span>
	        <span class="description">{{ housing.desc|truncatechars:200 }}</span>
	        <span>Адреса: {{ housing.address }}</span>
	        <span>Місткість: {{ housing.capacity }} чол.</span>
	        <span>Тип звукового обладнання: {{ housing.get_equipment_display }}</span>
	        <span class="info">Натиснiть для делальнои iнформацii...</span>
	    </div>
        <img src="{{ housing.logo_full|housing_logo_or_default }}">
	</div>
  </a>
    
    {% endfor %}

    <a href="/housings/"><span style="font-size: 28px;">Перейти до загального списку</span></a>
</div>
<br><br><br>
{% endblock %}

templates/navbar.html
{% load i18n %}
<nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Навігаційна панель</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Shop</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url "band:listing" %}">Гурти</a></li>
        <li><a href="{% url "housing:listing" %}">Примiщення</a></li>
        <li><a href="{% url "contact" %}">Контакти</a></li>
        {% if request.user.is_authenticated %}
            <li><a href="{% url "cart:index" %}">Корзина</a></li>
            <li><a href="{% url "profile:index" %}">{{ request.user.username }}</a></li>
        {% endif %}

        {% if request.user.is_authenticated %}
            {% if request.user.is_superuser %}
                <li><a href="{% url 'admin:index' %}">{% trans "SuperAdmin" %}</a></li>
            {% endif %}
            <li><a href="{% url 'account_logout' %}"><span class=" glyphicon glyphicon-log-out"></span>&nbsp;&nbsp;{% trans "Logout" %}</a></li>
        {% else %}
            <li><a href="{% url 'account_login' %}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;&nbsp;{% trans "Login" %}</a></li>
        {% endif %}

        </ul>
      </div>
    </div>
</nav>

templates/paginator.html
{% if pages|length > 1 %}
<div class="row">
<div class="col-xs-10 col-xs-offset-1">
     <ul class="pagination  pagination-lg">
        <li>
            {% if request.GET.search %}
                <a href="?search={{ request.GET.search }}&page={{ active_page|add:"-1" }}">
            {% else %}
                <a href="?page={{ active_page|add:"-1" }}">
            {% endif %}
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true" style="font-size: 24px;"></span></a>
        </li>
        {% for i in pages %}
            {% if active_page == i %}
                <li class="active">
            {% else %}
                <li>
            {% endif %}
            {% if request.GET.search %}
                <a href="?search={{ request.GET.search }}&page={{ i }}">
            {% else %}
                <a href="?page={{ i }}">
            {% endif %}
            {{ i }}</a>
        {% endfor %}

        <li>
            {% if request.GET.search %}
                <a href="?search={{ request.GET.search }}&page={{ active_page|add:"-1" }}">
            {% else %}
                <a href="?page={{ active_page|add:"1" }}">
            {% endif %}
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true" style="font-size: 24px;"></span></a>
        </li>
    </ul>
    </div>
</div>
{% endif %}

templates/popup.html
<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="gridSystemModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="gridSystemModalLabel"></h4>
      </div>
      <div id="modal-body" class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрити</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

templates/search.html
<form action="." method="get" class="searchbox">
    <input type="text" placeholder="Пошук" name="search">
    <button type="submit">Пошук</button>
</form>
<hr>